baseURL = "http://romanscollins.net/"
# languageCode = "en-us"
title = "Roman S. Collins"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "Roman S. Collins"
    profilePic = "/img/portrait.jpg"
    description = ""
    githubUsername = "RomanSC"
    accent = "#7F63A6"
    showBorder = true
    backgroundColor = "#f8f8f8"
    font = "Fira Sans"
    highlight = true
    highlightStyle = "github-gist"
    highlightLanguages = ["Bash", "Fish", "Python", "Ruby",
                          "HTML", "Markdown", "CSS", "JavaScript",
                          "TypeScript", "Lua", "Vim", "C",
                          "C++", "Rust", "Racket"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Blog"
    weight = 5

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:r.s.col988@gmail.com"
    name = "envelope"
    weight = 1

[[menu.icon]]
    url = "tel:802-490-9510"
    name = "phone"
    weight = 2

[[menu.icon]]
    url = "https://github.com/RomanSC/"
    name = "github"
    weight = 4

[[menu.icon]]
    url = "https://gitlab.com/RomanSC/"
    name = "gitlab"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/roman-collins-57697880/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://stackoverflow.com/users/10007897/romansc?tab=profile"
    name = "stack-overflow"
    weight = 5
