baseURL = "http://romanscollins.net/"
# languageCode = "en-us"
title = "Roman S. Collins"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "Roman S. Collins"
    description = ""
    githubUsername = "#"
    accent = "black"
    showBorder = false
    backgroundColor = "white"
    font = "Verdana"
    highlight = true
    highlightStyle = "monokai"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "C", "C++", "Rust", "Python", "JavaScript",
                          "TypeScrypt"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about.md"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:r.s.col988@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/RomanSC/"
    name = "github"
    weight = 4

[[menu.icon]]
    url = "https://gitlab.com/RomanSC/"
    name = "gitlab"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/roman-collins-57697880/"
    name = "linkedin"
    weight = 3

[[menu.icon]]
    url = "https://stackoverflow.com/users/10007897/romansc?tab=profile"
    name = "stack-overflow"
    weight = 5
